#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const targetDir = process.cwd();

function log(msg) {
  console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
}

function warn(msg) {
  console.log(`  \x1b[33m!\x1b[0m ${msg}`);
}

// Copy AGENTS.md to project root
const source = path.join(__dirname, 'AGENTS.md');
const dest = path.join(targetDir, 'AGENTS.md');

if (fs.existsSync(dest)) {
  warn('AGENTS.md already exists — overwriting');
}

fs.copyFileSync(source, dest);
log('Created AGENTS.md');

// Create symlinks for each AI agent
const symlinks = [
  { target: 'AGENTS.md', link: 'CLAUDE.md' },
  { target: 'AGENTS.md', link: '.cursorrules' },
  { target: path.join('..', 'AGENTS.md'), link: path.join('.github', 'copilot-instructions.md') },
  { target: path.join('..', 'AGENTS.md'), link: path.join('.gemini', 'styleguide.md') },
];

for (const { target, link } of symlinks) {
  const linkPath = path.join(targetDir, link);
  const linkDir = path.dirname(linkPath);

  // Ensure parent directory exists
  if (!fs.existsSync(linkDir)) {
    fs.mkdirSync(linkDir, { recursive: true });
  }

  // Remove existing file/symlink if present
  try {
    const stat = fs.lstatSync(linkPath);
    if (stat) fs.unlinkSync(linkPath);
  } catch {
    // File doesn't exist — nothing to remove
  }

  try {
    fs.symlinkSync(target, linkPath);
    log(`Symlinked ${link} → ${target}`);
  } catch (err) {
    // On Windows without symlink permissions, fall back to copy
    const resolvedTarget = path.resolve(targetDir, target);
    fs.copyFileSync(resolvedTarget, linkPath);
    warn(`Copied ${link} (symlink not supported — using copy)`);
  }
}

// OpenAI Codex CLI reads AGENTS.md at the repo root NATIVELY — unlike the agents
// above, it needs no symlink (it looks for AGENTS.md, not a tool-specific filename).
// A CODEX.md symlink would be inert. Instead we drop a project-scoped .codex/config.toml
// that marks the project Codex-aware and aligns its doc discovery with our AGENTS.md.
const codexDir = path.join(targetDir, '.codex');
const codexConfigPath = path.join(codexDir, 'config.toml');

if (!fs.existsSync(codexDir)) {
  fs.mkdirSync(codexDir, { recursive: true });
}

if (fs.existsSync(codexConfigPath)) {
  warn('.codex/config.toml already exists — leaving it untouched');
} else {
  const codexConfig = `# Codex CLI configuration — generated by @devground/agents-md
#
# Codex reads AGENTS.md from the repo root natively (no symlink needed),
# so the devground development rules already apply to Codex out of the box.
# These keys only tune how Codex discovers and ingests that doc.

# If AGENTS.md is ever missing, fall back to the Claude symlink (also -> AGENTS.md).
project_doc_fallback_filenames = ["CLAUDE.md"]

# Raise the default 32 KiB cap so the full AGENTS.md is always read as it grows.
project_doc_max_bytes = 65536
`;
  fs.writeFileSync(codexConfigPath, codexConfig);
  log('Created .codex/config.toml (Codex reads AGENTS.md natively)');
}

console.log(
  '\n  AGENTS.md installed for Claude, Cursor, Copilot, and Gemini (symlinks) and Codex (native + .codex/config.toml).\n',
);
